#!/usr/bin/zsh

REPO_LIST="${XDG_DATA_HOME:-$HOME/.local/share}/repo_list.json"
FZF_ARGS=(--height=12 --prompt=' Github ❯ ' --layout=reverse --scrollbar='█' --delimiter='/' '--nth=-1')
repo="$(jq -r '.[] | "\(.owner.login)/\(.name)"' "$REPO_LIST" | fzf "${FZF_ARGS[@]}")"
[[ -z "$repo" ]] && return
repo_name="$(basename "${repo%.git}")"
git clone "git@github.com:${repo}" ~/Code/"$repo_name"
cd ~/Code/"$repo_name"
