#!/usr/bin/zsh
emulate -L zsh
setopt nounset pipefail errreturn

remote="$(git remote -v | tail -n 1 | awk '{ print $2 }')"
if [[ ! $remote =~ https ]]; then
    remote="${remote/git@github.com:/https://github.com/}"
fi
# remove .git extention
remote="${remote%.git}"
$BROWSER "${remote}"
