#!/bin/zsh
emulate -L zsh
setopt nounset pipefail errreturn

# Keep in mind that all zenlib-*.zsh will be automatically sourced by zenlib
SSH_AGENT_ENV="$XDG_RUNTIME_DIR/zenlib-ssh-agent.zsh"

if [[ ! -f "$SSH_AGENT_ENV" ]]; then
    ssh-agent -t 10h > "$SSH_AGENT_ENV"
    source "$SSH_AGENT_ENV" > /dev/null
    ssh-add ~/.ssh/id_ed25519
fi
