#!/bin/zsh
emulate -L zsh
setopt no_unset pipe_fail err_return warn_create_global

typeset LOCATION="${1:-$HOME/Code}"

typeset REPO_LIST="${XDG_DATA_HOME:-$HOME/.local/share}/repo_list.json"

typeset -a FZF_ARGS
FZF_ARGS=(--height=12 --prompt=' Github ❯ ' --layout=reverse --scrollbar='█' --delimiter='/' '--nth=-1')

typeset repo="$(jq -r '.[] | "\(.owner.login)/\(.name)"' "$REPO_LIST" | fzf "${FZF_ARGS[@]}")"
[[ -z "$repo" ]] && return

typeset repo_name="$(basename "${repo%.git}")"
if [[ ! -d "$LOCATION/$repo_name" ]]; then
    git clone "git@github.com:${repo}" "$LOCATION/$repo_name"
fi
cd "$LOCATION/$repo_name"
