#!/bin/zsh
emulate -L zsh
setopt no_unset pipe_fail err_return warn_create_global

# To parse ZENLIB_GG_REPOLOC if glob expand to nothing
setopt null_glob

# Select a Git repository using fzf and go to that directory. If it's a
# Python project driven by poetry, try to source the virtual environment.

typeset -a ZENLIB_GG_REPOLOC
typeset -a ZENLIB_GG_SINGLES

if [[ -z ${ZENLIB_GG_REPOLOC:-} ]]; then
    ZENLIB_GG_REPOLOC="$HOME/Code"
fi

ZENLIB_GG_SINGLES=(~/.config/nvim ~/.vim)

typeset -a all_repos

all_repos+=($ZENLIB_GG_REPOLOC/*/*(/))

# Single repositories outside of ZENLIB_GG_REPOLOC path (like ~/.config/nvim for instance)
# If neede, set this variable in .zshrc for instance
if [[ -n ${ZENLIB_GG_SINGLES:-} ]]; then
    all_repos+=($ZENLIB_GG_SINGLES)
fi

typeset fzf_colors
fzf_colors=(
    input-border:#ff966c
    input-label:#ff966c
    list-border:#589ed7
    list-label:#589ed7
    preview-border:#589ed7
    preview-label:#589ed7
    header-border:#c3e88d
    header-label:#c3e88d
    hl:#61b4f5
    current-hl:#61b4f5
    current-bg:#2d3f76
    current-fg:#d9def2:bold
    pointer:-1
    info:#545c7e
)

typeset -a fzf_args
fzf_args=(
    --prompt='→ '
    --gutter=' '
    --delimiter='/'
    --with-nth='-2,-1'
    --nth='-1'
    --input-border='rounded'
    --input-label=' Filter '
    --list-border='rounded'
    --list-label=' Repositories '
    --preview-border='rounded'
    --preview-label=' Preview '
    --header-border='rounded'
    --header-label=' Branch '
    --no-info
    --color="${(j:,:)fzf_colors}"
    --margin='10%'
    --no-scrollbar
    --info='inline-right'
    --cycle
    --no-mouse
    --preview='tree -L 1 -C --dirsfirst {}'
    --bind='focus:transform-header:git -C {} branch --show-current || echo "No branch checked out"'
)

typeset repo="$(print -l $all_repos | fzf "${fzf_args[@]}")"

# Dont do anything if nothing is selected
if [[ -z "$repo" ]]; then
    return
fi

cd "$repo"
print "\033[34mOwner  \033[32m$(git remote get-url origin | sed -E 's;.*github\.com.(.*)/.*;\1;g')"
print "\033[34mRepo   \033[32m${repo:t}"

# Try to deactivate Python venv
if command -v deactivate > /dev/null 2>&1; then
    deactivate
fi

# We could try to use "poetry env info --path" but the result of this command
# depends on the poetry version currently in use.
# Make sure poetry will create venv inside the project. For instance put this
# in your ~/.profile or ~/.zprofile :
# export POETRY_VIRTUALENVS_IN_PROJECT='true'
if [[ -d .venv ]]; then
    emulate -L zsh; source .venv/bin/activate
    print "\033[34mVenv   \033[32m${VIRTUAL_ENV_PROMPT}"
fi
