#!/bin/zsh
emulate -L zsh
setopt no_unset pipe_fail err_return warn_create_global

# Select a Git repository using fzf and go to that directory. If it's a
# Python project driven by poetry, try to source the virtual environment.

if [[ -z ${ZENLIB_REPO_LOCATIONS:-} ]]; then
    zlog error 'You should define an array named ZENLIB_REPO_LOCATIONS to use this function'
    return 1
fi

typeset repo="$(find "${ZENLIB_REPO_LOCATIONS[@]}" -maxdepth 1 -mindepth 1 -type d | fzf -d '/' --with-nth='-1' --height=20 --layout=reverse --scrollbar='█' --preview='tree -L 1 -C --dirsfirst {}')"

# Dont do anything if nothing is selected
if [[ -z "$repo" ]]; then
    return
fi

cd "$repo"

# Try to deactivate Python venv
if command -v deactivate > /dev/null 2>&1; then
    deactivate
fi

# Try to source new Python venv
if [[ -f pyproject.toml ]] && [[ -d "$(poetry env info --path)" ]]; then
    emulate -L zsh; source "$(poetry env info --path)"/bin/activate
fi

echo "  ${PWD/$HOME/~}"
