#!/bin/zsh
emulate -L zsh
setopt no_unset pipe_fail err_return warn_create_global

# tokyonight moon palette
typeset -A tokyonight
tokyonight=(
    # bg '#222436'
    bg_dark '#1e2030'
    bg_dark1 '#191B29'
    bg_highlight '#2f334d'
    blue '#82aaff'
    blue0 '#3e68d7'
    blue1 '#65bcff'
    blue2 '#0db9d7'
    blue5 '#89ddff'
    blue6 '#b4f9f8'
    blue7 '#394b70'
    comment '#636da6'
    cyan '#86e1fc'
    dark3 '#545c7e'
    dark5 '#737aa2'
    # fg '#c8d3f5'
    fg_dark '#828bb8'
    fg_gutter '#3b4261'
    green '#c3e88d'
    green1 '#4fd6be'
    green2 '#41a6b5'
    magenta '#c099ff'
    magenta2 '#ff007c'
    orange '#ff966c'
    purple '#fca7ea'
    red '#ff757f'
    red1 '#c53b53'
    teal '#4fd6be'
    terminal_black '#444a73'
    yellow '#ffc777'
)

# I already know the aliases I defined, no need to differenciate them
ZSH_HIGHLIGHT_STYLES[command]="fg=${tokyonight[blue]}"
ZSH_HIGHLIGHT_STYLES[alias]="fg=${tokyonight[blue]}"

# Actually, precommands are builtins, so it make sense to have the same color for both
ZSH_HIGHLIGHT_STYLES[function]="fg=${tokyonight[blue1]}"
ZSH_HIGHLIGHT_STYLES[builtin]="fg=${tokyonight[blue1]}"
ZSH_HIGHLIGHT_STYLES[precommand]="fg=${tokyonight[blue1]},underline"
ZSH_HIGHLIGHT_STYLES[autodirectory]="fg=${tokyonight[blue1]},bold"

# Pretty options
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]="fg=${tokyonight[yellow]}"
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]="fg=${tokyonight[yellow]}"

# Reserved words like if / then / else / for etc.
ZSH_HIGHLIGHT_STYLES[reserved-word]="fg=${tokyonight[magenta]}"

# Strings
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]="fg=${tokyonight[green]}"
ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]="fg=${tokyonight[green]}"
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]="fg=${tokyonight[green]}"
ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]="fg=${tokyonight[green]}"

# Comments
ZSH_HIGHLIGHT_STYLES[comment]="fg=${tokyonight[comment]}"

ZSH_HIGHLIGHT_STYLES[commandseparator]="fg=${tokyonight[blue5]}"
ZSH_HIGHLIGHT_STYLES[redirection]="fg=${tokyonight[blue5]}"
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]="fg=${tokyonight[blue5]}"
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]="fg=${tokyonight[blue5]}"
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]="fg=${tokyonight[blue5]}"

ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]="fg=${tokyonight[orange]}"
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]="fg=${tokyonight[orange]}"
ZSH_HIGHLIGHT_STYLES[history-expansion]="fg=${tokyonight[orange]}"

ZSH_HIGHLIGHT_STYLES[bracket-error]="fg=${tokyonight[red]},bold"
ZSH_HIGHLIGHT_STYLES[unknown-token]="fg=${tokyonight[red]}"

ZSH_HIGHLIGHT_STYLES[globbing]="fg=${tokyonight[teal]}"
ZSH_HIGHLIGHT_STYLES[path]="fg=${tokyonight[teal]}"
ZSH_HIGHLIGHT_STYLES[path_pathseparator]="fg=${tokyonight[green]},bold"

ZSH_HIGHLIGHT_STYLES[global-alias]="fg=${tokyonight[teal]},standout"


# Highlighters order matters: regexp should be first, as it will be overriden by the main highlighter
# Thus for `print $HOME '$HOME'` the first $HOME will be highlighted with regexp, and the second with the main highlighter.
ZSH_HIGHLIGHT_HIGHLIGHTERS=(regexp $ZSH_HIGHLIGHT_HIGHLIGHTERS)
typeset -g RE_MATCH_PCRE=1
typeset -gA ZSH_HIGHLIGHT_REGEXP

# NOTE hopefully in future versions of zsh-zyntax-highlighting variables will be highlighted natively
# Should work with the following:
#   $var
#   ${var}
#   ${#var}
#   ${var[@]}
#   ${var[1]}
#   ${var:u:t}
ZSH_HIGHLIGHT_REGEXP+=('\$\{?#?\w+(\[.\])?(:\w)*\}?' "fg=${tokyonight[orange]}")
