#!/bin/zsh
emulate -L zsh
# No options here because we source external files

typeset plugdir="${XDG_DATA_HOME:-$HOME/.local/share}/zsh/plugins"

case "$1" in
    load)
        shift
        typeset org="$1"
        typeset repo="$2"
        typeset initfile="$3"

        [[ -d $plugdir ]] || mkdir -p "$plugdir"
        [[ -d "${plugdir}/${repo}" ]] || git -C "$plugdir" clone --depth 1 -- "https://github.com/${org}/${repo}.git"
        . "${plugdir}/${repo}/${initfile}"
        ;;
    update)
        typeset plugin; for plugin in "$plugdir"/*(/); do
            print "Updating plugin ${plugin:t}..."
            git -C "$plugin" pull
            print 'Done'
        done
        ;;
    *)
        print "Invalid subcommand $1"
        return 1
        ;;
esac
