#!/bin/zsh
emulate -L zsh
setopt no_unset pipe_fail err_return warn_create_global

declare -A color
color=(debug '\033[1;37m' info '\033[1;32m' warning '\033[1;33m' error '\033[1;31m')

typeset level="$1" && shift
print "${color[$level]}$(date '+%Y-%m-%d %H:%M:%S') - ${level:u} - $*\033[0m"
